import { createFileRoute } from "@tanstack/react-router";
import { Download, Search } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { DashboardHeader } from "@/components/dashboard-header";
import { ReportStatusBadge } from "@/components/rpa-badges";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { reportHistory } from "@/lib/rpa-data";

export const Route = createFileRoute("/report-history")({
  head: () => ({
    meta: [
      { title: "Report History — RPA Automation Reporting" },
      {
        name: "description",
        content: "Every report generated by the automation platform, ready to download.",
      },
      { property: "og:title", content: "Report History — RPA Automation Reporting" },
      {
        property: "og:description",
        content: "Download past automation reports and track generation status.",
      },
    ],
  }),
  component: ReportHistoryPage,
});

function ReportHistoryPage() {
  const [query, setQuery] = useState("");
  const rows = reportHistory.filter((r) =>
    (r.id + r.useCase + r.type).toLowerCase().includes(query.toLowerCase()),
  );

  return (
    <>
      <DashboardHeader title="Report History" subtitle="Previously generated automation reports" />
      <main className="flex-1 space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        <div className="relative max-w-xs">
          <Search className="pointer-events-none absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search report..."
            className="rounded-full pl-9"
          />
        </div>

        <div className="surface-card overflow-hidden hover:shadow-none">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead>Report ID</TableHead>
                  <TableHead>Use Case</TableHead>
                  <TableHead className="min-w-40">Type</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Generated At</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="w-12" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {rows.map((r) => (
                  <TableRow key={r.id}>
                    <TableCell className="text-sm font-semibold">{r.id}</TableCell>
                    <TableCell className="text-sm">{r.useCase}</TableCell>
                    <TableCell className="text-sm">{r.type}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">{r.period}</TableCell>
                    <TableCell className="text-xs whitespace-nowrap text-muted-foreground">
                      {r.generatedAt}
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground">{r.size}</TableCell>
                    <TableCell>
                      <ReportStatusBadge status={r.status} />
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="rounded-full"
                        disabled={r.status !== "Ready"}
                        aria-label={`Download ${r.id}`}
                        onClick={() =>
                          toast.success("Download started", {
                            description: `${r.id} — ${r.type} (${r.period})`,
                          })
                        }
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
                {rows.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={8} className="py-10 text-center text-sm text-muted-foreground">
                      No report matches your search.
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </div>
        </div>
      </main>
    </>
  );
}
